- type: rank
  id: RMCRankVAIMercenary
  name: "Найманець VAI"
  prefix: Merc.

- type: rank
  id: RMCRankVAIMedicalSpecialist
  name: "Медичний Спеціаліст VAI"
  prefix: Med.

- type: rank
  id: RMCRankVAIMachinegunner
  name: "Кулеметник VAI"
  prefix: MG.

- type: rank
  id: RMCRankVAIEngineeringSpecialist
  name: "Інженерний Спеціаліст VAI"
  prefix: Eng.

- type: rank
  id: RMCRankVAISynthetic
  name: "Синтетик VAI"
  prefix: Syn.

- type: rank
  id: RMCRankVAITeamLeader
  name: "Лідер Команди VAI"
  prefix: TL.