- type: rank
  id: RMCRankFLFreelancer
  name: "Найманець"
  prefix: Merc.

- type: rank
  id: RMCRankFLMedic
  name: "Медик"
  prefix: Med.

- type: rank
  id: RMCRankFLLeader
  name: "Лідер"
  prefix: Warlord

- type: rank
  id: RMCRankFLEliteFreelancer
  name: "Елітний"
  prefix: Merc.

- type: rank
  id: RMCRankFLEliteHeavy
  name: "Елітний Важкий"
  prefix: Hvy.

- type: rank
  id: RMCRankFLEliteEngineer
  name: "Елітний Інженер"
  prefix: Eng.

- type: rank
  id: RMCRankFLEliteMedic
  name: "Елітний Медик"
  prefix: Med.

- type: rank
  id: RMCRankFLEliteLeader
  name: "Елітний Лідер"
  prefix: Warlord
