# combat technician
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidBravoCombatTech
  name: "браво привид-роль бойового техніка"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCBravoCombatTech

- type: randomHumanoidSettings
  parent: [RMCCombatTech, RMCBravoBase]
  id: RMCBravoCombatTech

# fireteam leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidBravoFireteamLeader
  name: "браво привид-роль лідера вогневої команди"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCBravoFireteamLeader

- type: randomHumanoidSettings
  parent: [RMCFireteamLeader, RMCBravoBase]
  id: RMCBravoFireteamLeader

# hospital corpsman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidBravoHospitalCorpsman
  name: "браво привид-роль шпитального корпсмена"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCBravoHospitalCorpsman

- type: randomHumanoidSettings
  parent: [RMCHospitalCorpsman, RMCBravoBase]
  id: RMCBravoHospitalCorpsman

# rifleman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidBravoRifleman
  name: "браво привид-роль стрільця"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCBravoRifleman

- type: randomHumanoidSettings
  parent: [RMCRifleman, RMCBravoBase]
  id: RMCBravoRifleman

# smart gun operator
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidBravoSmartGunOperator
  name: "браво привид-роль оператора смартгана"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCBravoSmartGunOperator

- type: randomHumanoidSettings
  parent: [RMCSmartGunOperator, RMCBravoBase]
  id: RMCBravoSmartGunOperator

# squad leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidBravoSquadLeader
  name: "браво привид-роль лідера загону"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCBravoSquadLeader

- type: randomHumanoidSettings
  parent: [RMCSquadLeader, RMCBravoBase]
  id: RMCBravoSquadLeader

# weapons specialist
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidBravoWeaponsSpecialist
  name: "браво привид-роль спеціаліста з озброєння"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCBravoWeaponsSpecialist

- type: randomHumanoidSettings
  parent: [RMCWeaponsSpecialist, RMCBravoBase]
  id: RMCBravoWeaponsSpecialist
