# combat technician
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidCharlieCombatTech
  name: "чарлі привид-роль бойового техніка"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCCharlieCombatTech

- type: randomHumanoidSettings
  parent: [RMCCombatTech, RMCCharlieBase]
  id: RMCCharlieCombatTech

# fireteam leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidCharlieFireteamLeader
  name: "чарлі привид-роль лідера вогневої команди"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCCharlieFireteamLeader

- type: randomHumanoidSettings
  parent: [RMCFireteamLeader, RMCCharlieBase]
  id: RMCCharlieFireteamLeader

# hospital corpsman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidCharlieHospitalCorpsman
  name: "чарлі привид-роль шпитального корпсмена"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCCharlieHospitalCorpsman

- type: randomHumanoidSettings
  parent: [RMCHospitalCorpsman, RMCCharlieBase]
  id: RMCCharlieHospitalCorpsman

# rifleman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidCharlieRifleman
  name: "чарлі привид-роль стрільця"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCCharlieRifleman

- type: randomHumanoidSettings
  parent: [RMCRifleman, RMCCharlieBase]
  id: RMCCharlieRifleman

# smart gun operator
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidCharlieSmartGunOperator
  name: "чарлі привид-роль оператора смартгана"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCCharlieSmartGunOperator

- type: randomHumanoidSettings
  parent: [RMCSmartGunOperator, RMCCharlieBase]
  id: RMCCharlieSmartGunOperator

# squad leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidCharlieSquadLeader
  name: "чарлі привид-роль лідера загону"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCCharlieSquadLeader

- type: randomHumanoidSettings
  parent: [RMCSquadLeader, RMCCharlieBase]
  id: RMCCharlieSquadLeader

# weapons specialist
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidCharlieWeaponsSpecialist
  name: "чарлі привид-роль спеціаліста з озброєння"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCCharlieWeaponsSpecialist

- type: randomHumanoidSettings
  parent: [RMCWeaponsSpecialist, RMCCharlieBase]
  id: RMCCharlieWeaponsSpecialist
