# combat technician
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaCombatTech
  name: "дельта привид-роль бойового техніка"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaCombatTech

- type: randomHumanoidSettings
  parent: [RMCCombatTech, RMCDeltaBase]
  id: RMCDeltaCombatTech

# fireteam leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaFireteamLeader
  name: "дельта привид-роль лідера вогневої команди"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaFireteamLeader

- type: randomHumanoidSettings
  parent: [RMCFireteamLeader, RMCDeltaBase]
  id: RMCDeltaFireteamLeader

# hospital corpsman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaHospitalCorpsman
  name: "дельта привид-роль шпитального корпсмена"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaHospitalCorpsman

- type: randomHumanoidSettings
  parent: [RMCHospitalCorpsman, RMCDeltaBase]
  id: RMCDeltaHospitalCorpsman

# rifleman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaRifleman
  name: "дельта привид-роль стрільця"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaRifleman

- type: randomHumanoidSettings
  parent: [RMCRifleman, RMCDeltaBase]
  id: RMCDeltaRifleman

# smart gun operator
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaSmartGunOperator
  name: "дельта привид-роль оператора смартгана"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaSmartGunOperator

- type: randomHumanoidSettings
  parent: [RMCSmartGunOperator, RMCDeltaBase]
  id: RMCDeltaSmartGunOperator

# squad leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaSquadLeader
  name: "дельта привид-роль лідера загону"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaSquadLeader

- type: randomHumanoidSettings
  parent: [RMCSquadLeader, RMCDeltaBase]
  id: RMCDeltaSquadLeader

# weapons specialist
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidDeltaWeaponsSpecialist
  name: "дельта привид-роль спеціаліста з озброєння"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCDeltaWeaponsSpecialist

- type: randomHumanoidSettings
  parent: [RMCWeaponsSpecialist, RMCDeltaBase]
  id: RMCDeltaWeaponsSpecialist
