# combat technician
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidIntelCombatTech
  name: "розвідка привид-роль бойового техніка"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCIntelCombatTech

- type: randomHumanoidSettings
  parent: [RMCCombatTech, RMCIntelBase]
  id: RMCIntelCombatTech

# fireteam leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidIntelFireteamLeader
  name: "розвідка привид-роль лідера вогневої команди"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCIntelFireteamLeader

- type: randomHumanoidSettings
  parent: [RMCFireteamLeader, RMCIntelBase]
  id: RMCIntelFireteamLeader

# hospital corpsman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidIntelHospitalCorpsman
  name: "розвідка привид-роль шпитального корпсмена"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCIntelHospitalCorpsman

- type: randomHumanoidSettings
  parent: [RMCHospitalCorpsman, RMCIntelBase]
  id: RMCIntelHospitalCorpsman

# rifleman
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidIntelRifleman
  name: "розвідка привид-роль стрільця"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCIntelRifleman

- type: randomHumanoidSettings
  parent: [RMCRifleman, RMCIntelBase]
  id: RMCIntelRifleman

# smart gun operator
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidIntelSmartGunOperator
  name: "розвідка привид-роль оператора смартгана"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCIntelSmartGunOperator

- type: randomHumanoidSettings
  parent: [RMCSmartGunOperator, RMCIntelBase]
  id: RMCIntelSmartGunOperator

# squad leader
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidIntelSquadLeader
  name: "розвідка привид-роль лідера загону"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCIntelSquadLeader

- type: randomHumanoidSettings
  parent: [RMCSquadLeader, RMCIntelBase]
  id: RMCIntelSquadLeader

# weapons specialist
- type: entity
  parent: MarkerBase
  id: RMCRandomHumanoidIntelWeaponsSpecialist
  name: "розвідка привид-роль спеціаліста з озброєння"
  suffix: Spawner, Player
  components:
  - type: Sprite
    layers:
    - state: red
  - type: RandomHumanoidSpawner
    settings: RMCIntelWeaponsSpecialist

- type: randomHumanoidSettings
  parent: [RMCWeaponsSpecialist, RMCIntelBase]
  id: RMCIntelWeaponsSpecialist
