# riot
- type: entity
  parent: [RMCHelmetBase, RMCFoldableHelmetBase]
  id: ArmorHelmetRiot
  name: "шолом для придушення заворушень"
  description: "Це шолом, спеціально створений для захисту від атак на близькій відстані. Закриває вуха."
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Head/Helmets/riot.rsi
  - type: Clothing
    sprite: _RMC14/Objects/Clothing/Head/Helmets/riot.rsi
  - type: CMArmor
    melee: 30
    bullet: 10
    # armor_laser = 10
    # armor_energy = 10
    # armor_internaldamage = 25
  - type: CMHardArmor

- type: entity
  parent: ArmorHelmetRiot
  id: ArmorHelmetRiotOld
  description: "Побитий шолом для придушення заворушень BA, вкритий павутинням. Він досі захищає ваші вуха."
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Head/Helmets/old_riot.rsi
    layers:
    - state: icon
  - type: Clothing
    sprite: _RMC14/Objects/Clothing/Head/Helmets/old_riot.rsi
    equipDelay: 2
    unequipDelay: 2

# basic
- type: entity
  parent: [RMCHelmetBase, RMCFoldableHelmetBase]
  id: RMCArmorHelmetSecurity
  name: "шолом"
  description: "Стандартне захисне спорядження. Захищає голову від ударів."
  components:
  - type: Sprite
    sprite: _RMC14/Objects/Clothing/Head/Helmets/security.rsi
  - type: Clothing
    sprite: _RMC14/Objects/Clothing/Head/Helmets/security.rsi
  - type: CMArmor
    melee: 20
    bullet: 15
    # armor_laser = 10
    # armor_energy = 10
    # armor_internaldamage = 20
