- type: job
  parent: RMCSurvivorShivasDoctor
  id: RMCSurvivorShivasPanicRoomDoctor
  name: rmc-job-name-survivor-shivas-doctor
  playTimeTracker: CMJobSurvivorDoctor
  startingGear: RMCGearSurvivorShivasDoctor
  spawnMenuRoleName: Doctor (Shivas Panic Room Special Survivor)
  greeting: rmc-job-greeting-shivas-panic-room-doctor

- type: entity
  parent: RMCSpawnPointSurvivorShivasDoctor
  id: RMCSpawnPointSurvivorShivasPanicRoomDoctor
  name: "спавнер спецлікаря панік-кімнати шиви"
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorShivasPanicRoomDoctor
