- type: job
  parent: CMSurvivor
  id: RMCSurvivorShivasPanicRoomCivilian
  name: cm-job-name-survivor
  spawnMenuRoleName: Civilian (Shivas Panic Room Special Survivor)
  playTimeTracker: CMJobSurvivor

- type: entity
  parent: CMSpawnPointSurvivor
  id: CMSpawnPointPanicRoomSurvivor
  name: "спавнер спеццивільного-вцілілого панік-кімнати"
  components:
  - type: SpawnPoint
    job_id: RMCSurvivorShivasPanicRoomCivilian
