- type: entity
  name: "коробка з наручниками"
  parent: BoxCardboard
  id: BoxHandcuff
  description: "Коробка, повна наручників."
  components:
  - type: StorageFill
    contents:
    - id: Handcuffs
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: handcuff

- type: entity
  name: "коробка стяжок"
  parent: BoxCardboard
  id: BoxZiptie
  description: "Коробка, повна стяжок."
  components:
  - type: StorageFill
    contents:
    - id: Zipties
      amount: 9
  - type: Sprite
    layers:
    - state: box_security
    - state: ziptie

- type: entity
  name: "коробка світлошумових гранат"
  parent: BoxCardboard
  id: BoxFlashbang
  description: "ПОПЕРЕДЖЕННЯ: Ці пристрої надзвичайно небезпечні і можуть спричинити сліпоту або глухоту при повторних використаннях."
  components:
  - type: StorageFill
    contents:
    - id: GrenadeFlashBang
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: "коробка з жалячими гранатами"
  parent: BoxCardboard
  id: BoxStinger
  description: "Коробка, повна жалячих гранат. Розсіюйтеся!"
  components:
  - type: StorageFill
    contents:
    - id: GrenadeStinger
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: "коробка зі сльозогінним газом"
  parent: BoxCardboard
  id: BoxTearGas
  description: "Коробка, повна гранат зі сльозогінним газом. Затамуйте подих."
  components:
  - type: StorageFill
    contents:
    - id: TearGasGrenade
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: "коробка з sechud"
  parent: BoxCardboard
  id: BoxSechud
  description: "Коробка з sechuds."
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesHudSecurity
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: sechud

- type: entity
  name: "коробка з окулярами СБ"
  parent: BoxCardboard
  id: BoxSecglasses
  description: "Коробка з окулярами служби безпеки."
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesGlassesSecurity
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: secglasses

- type: entity
  name: "коробка з сонцезахисними окулярами"
  parent: BoxCardboard
  id: BoxSunglasses
  description: "Коробка з крутими сонцезахисними окулярами, що захищають від спалахів."
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesGlassesSunglasses
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: sunglasses

- type: entity
  name: "коробка з криміналістичними папірцями"
  parent: BoxCardboard
  id: BoxForensicPad
  description: "Коробка криміналістичного папіру."
  components:
  - type: Item
    shape:
    - 0,0,1,1
  - type: StorageFill
    contents:
    - id: ForensicPad
      amount: 9
  - type: Sprite
    layers:
    - state: box_security
    - state: forensic
