- type: entity
  id: AU14SkillPresetPlatoonRifleman
  name: "стрілець"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 1
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillEngineer: 1
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillJtac: 1

- type: entity
  id: AU14SkillPresetPlatoonRTO
  name: "оператор радіозв’язку"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 1
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillEngineer: 1
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillJtac: 4

- type: entity
  id: AU14SkillPresetPlatoonAutomaticRifleman
  name: "автоматник"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 1
      RMCSkillCqc: 1
      RMCSkillEndurance: 2
      RMCSkillEngineer: 1
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillSmartGun: 1
      RMCSkillJtac: 1

- type: entity
  id: AU14SkillPresetPlatoonHospitalCorpsman
  name: "госпітальний корпусман"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 1
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillEngineer: 1
      RMCSkillFirearms: 1
      RMCSkillFireman: 3
      RMCSkillVehicles: 1
      RMCSkillMedical: 2
      RMCSkillSurgery: 1
      RMCSkillJtac: 1

- type: entity
  id: AU14SkillPresetPlatoonCombatTechnician
  name: "бойовий технік"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 4
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillEngineer: 4
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillJtac: 2
      RMCSkillPowerLoader: 2

- type: entity
  id: AU14SkillPresetPlatoonSergeant
  name: "сержант"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillLeadership: 2
      RMCSkillJtac: 3
      RMCSkillCqc: 1
      RMCSkillFirearms: 2
      RMCSkillEndurance: 2
      RMCSkillConstruction: 2
      RMCSkillEngineer: 3
      RMCSkillFireman: 2
      RMCSkillPolice: 1
      RMCSkillVehicles: 1

- type: entity
  id: AU14SkillPresetPlatoonSeniorSergeant
  name: "старший сержант"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 2
      RMCSkillCqc: 2
      RMCSkillEndurance: 3
      RMCSkillEngineer: 2
      RMCSkillFirearms: 2 #gunny has more time on the range than the entire platoon, rumour is he rucks 20 miles a day just to get a weyburger
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillOverwatch: 1
      RMCSkillPilot: 1
      RMCSkillLeadership: 3
      RMCSkillIntel: 1
      RMCSkillPowerLoader: 1
      RMCSkillMedical: 1
      RMCSkillSurgery: 1
      RMCSkillNavigations: 1
      RMCSkillPolice: 1
      RMCSkillJtac: 4

- type: entity
  id: AU14SkillPresetPlatoonJuniorOfficer
  name: "молодший офіцер"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillLeadership: 3
      RMCSkillJtac: 3
      RMCSkillNavigations: 1
      RMCSkillOverwatch: 1
      RMCSkillIntel: 2
      RMCSkillCqc: 2
      RMCSkillFirearms: 1
      RMCSkillEndurance: 1
      RMCSkillPilot: 1
      RMCSkillEngineer: 2
      RMCSkillConstruction: 2
      RMCSkillPowerLoader: 1
      RMCSkillVehicles: 1
      RMCSkillFireman: 1 #fat second el-tee
      RMCSkillMedical: 1
      RMCSkillSurgery: 1
      RMCSkillPolice: 2

- type: entity
  id: AU14SkillPresetPlatoonCommander
  name: "командир"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillLeadership: 4
      RMCSkillJtac: 4
      RMCSkillNavigations: 1
      RMCSkillOverwatch: 1
      RMCSkillIntel: 2
      RMCSkillCqc: 2
      RMCSkillFirearms: 2
      RMCSkillEndurance: 3
      RMCSkillPilot: 1
      RMCSkillEngineer: 3
      RMCSkillConstruction: 3
      RMCSkillPowerLoader: 2
      RMCSkillVehicles: 1
      RMCSkillFireman: 2
      RMCSkillMedical: 3
      RMCSkillSurgery: 1
      RMCSkillPolice: 2

- type: entity
  id: AU14SkillPresetPlatoonAdvisor
  name: "радник"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 4
      RMCSkillCqc: 4
      RMCSkillEndurance: 4
      RMCSkillEngineer: 4
      RMCSkillFirearms: 2
      RMCSkillFireman: 3
      RMCSkillVehicles: 2
      RMCSkillOverwatch: 1
      RMCSkillPilot: 2
      RMCSkillLeadership: 2
      RMCSkillIntel: 2
      RMCSkillPowerLoader: 2
      RMCSkillMedical: 4
      RMCSkillSurgery: 4
      RMCSkillNavigations: 1
      RMCSkillPolice: 2
      RMCSkillJtac: 4

- type: entity
  id: AU14SkillPresetPlatoonDP
  name: "пілот десантного корабля"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 2
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillEngineer: 2
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 2
      RMCSkillOverwatch: 1
      RMCSkillPilot: 2
      RMCSkillLeadership: 3
      RMCSkillIntel: 2
      RMCSkillPowerLoader: 2
      RMCSkillMedical: 2
      RMCSkillSurgery: 1
      RMCSkillNavigations: 1
      RMCSkillPolice: 1
      RMCSkillJtac: 3

- type: entity
  id: AU14SkillPresetPlatoonDCC
  name: "старшина екіпажу десантного корабля"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 1
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillEngineer: 1
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 2
      RMCSkillPilot: 2
      RMCSkillIntel: 1
      RMCSkillPowerLoader: 2
      RMCSkillMedical: 2
      RMCSkillSurgery: 1
      RMCSkillNavigations: 1
      RMCSkillPolice: 1
      RMCSkillJtac: 4

- type: entity
  id: AU14SkillPresetPlatoonAuxiliarySupportSynth
  name: "допоміжний синтетик підтримки"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillCqc: 5
      RMCSkillEndurance: 1
      RMCSkillEngineer: 4
      RMCSkillConstruction: 3
      RMCSkillFirearms: 2
      RMCSkillOverwatch: 1
      RMCSkillMedical: 4
      RMCSkillSurgery: 3
      RMCSkillResearch: 1
      RMCSkillMeleeWeapons: 2
      RMCSkillPilot: 2
      RMCSkillPolice: 2
      RMCSkillFireman: 5
      RMCSkillPowerLoader: 2
      RMCSkillVehicles: 2
      RMCSkillJtac: 3
      RMCSkillIntel: 2
      RMCSkillDomestics: 2
      RMCSkillNavigations: 1

- type: entity
  id: AU14SkillPresetMilitaryDoctor
  name: "військовий лікар"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillOverwatch: 1
      RMCSkillLeadership: 1
      RMCSkillIntel: 1
      RMCSkillMedical: 4
      RMCSkillSurgery: 4
      RMCSkillPolice: 1

- type: entity
  id: AU14SkillPresetPlatoonWorkingJoe
  name: "Воркінг Джо"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillCqc: 5
      RMCSkillEndurance: 1
      RMCSkillEngineer: 4
      RMCSkillConstruction: 4
      RMCSkillFirearms: 1
      RMCSkillMeleeWeapons: 2
      RMCSkillPolice: 2
      RMCSkillFireman: 5
      RMCSkillPowerLoader: 2
      RMCSkillVehicles: 2
      RMCSkillDomestics: 2

- type: entity
  id: AU14SkillPresetMilitaryPolice
  name: "військова поліція"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 1
      RMCSkillCqc: 3
      RMCSkillEndurance: 2
      RMCSkillEngineer: 1
      RMCSkillOverwatch: 1
      RMCSkillFirearms: 1
      RMCSkillFireman: 3
      RMCSkillVehicles: 1
      RMCSkillJtac: 1
      RMCSkillPolice: 2

- type: entity
  id: AU14SkillPresetPlatoonAuxTech
  name: "допоміжний технік"
  categories: [ HideSpawnMenu ]
  components:
  - type: SkillPreset
    skills:
      RMCSkillConstruction: 4
      RMCSkillCqc: 1
      RMCSkillEndurance: 1
      RMCSkillEngineer: 4
      RMCSkillFirearms: 1
      RMCSkillFireman: 2
      RMCSkillVehicles: 1
      RMCSkillJtac: 2
      RMCSkillPowerLoader: 2
      RMCSkillIntel: 1
      RMCSkillDomestics: 2
