# TSEPA - (Three Suns Empire Policing Authority) - TSE style Police, like the CMB but for heavy TSE focused colonies. Please change when we have a new name for the sector.

- type: rank
  id: RMCRankTSEPAConstable
  name: "Констебль"
  prefix: Cst.

- type: rank
  id: RMCRankTSEPASeniorConstable
  name: "Старший Констебль"
  prefix: Sr. Cst.

- type: rank
  id: RMCRankTSEPASergeant
  name: "Сержант"
  prefix: Sgt.

- type: rank
  id: RMCRankTSEPAInspector
  name: "Інспектор"
  prefix: Insp.

- type: rank
  id: RMCRankTSEPAChiefInspector
  name: "Головний Інспектор"
  prefix: Ch. Insp.

- type: rank
  id: RMCRankTSEPACommander
  name: "Командор"
  prefix: Cmdr.

- type: rank
  id: RMCRankTSEPADeputyCommissioner
  name: "Заступник Комісара"
  prefix: Dep. Com.

- type: rank
  id: RMCRankTSEPACommissioner
  name: "Комісар"
  prefix: Com.

