- type: rank
  id: AU14RankCMBProbDeputy
  name: "заступник на випробувальному терміні"
  prefix: Prob. Dep.

- type: rank
  id: AU14RankCMBDeputy
  name: "заступник"
  prefix: Dep.

- type: rank
  id: AU14RankCMBSrDeputy
  name: "старший заступник"
  prefix: Sr. Dep.

- type: rank
  id: AU14RankCMBChiefDeputy
  name: "головний заступник"
  prefix: Chf. Dep.

- type: rank
  id: AU14RankCMBMarshal
  name: "маршал CMB"
  prefix: Mrshl.

- type: rank
  id: AU14RankColonyAdministrator
  name: "адміністратор"
  prefix: Admin.

- type: rank
  id: AU14RankColonySeniorAdministrator
  name: "старший адміністратор"
  prefix: Sr. Admin.

- type: rank
  id: AU14RankCWPSRangerTrainee
  name: "рейнджер на випробувальному терміні"
  prefix: Prob. Ranger

- type: rank
  id: AU14RankCWPSRanger
  name: "рейнджер"
  prefix: Ranger

- type: rank
  id: AU14RankCWPSSeniorRanger
  name: "старший рейнджер"
  prefix: Sr. Ranger

- type: rank
  id: AU14RankNSPAConstable
  name: "констебль"
  prefix: Constable

- type: rank
  id: AU14RankNSPASeniorConstable
  name: "старший констебль"
  prefix: Sr. Constable

- type: rank
  id: AU14RankNSPAInspector
  name: "інспектор"
  prefix: Insp.

# Scientists

- type: rank
  id: AU14RankScientistAssistant
  name: "асистент-професор"
  prefix: Assist-Prof.

- type: rank
  id: AU14RankScientistAssociate
  name: "доцент"
  prefix: Asso-Prof.

- type: rank
  id: AU14RankScientistProfessor
  name: "професор"
  prefix: Prof.

# Commercial Pilots

- type: rank
  id: AU14RankFirstOfficer
  name: "перший офіцер"
  prefix: 1st Off.

- type: rank
  id: AU14RankSeniorFirstOfficer
  name: "старший перший офіцер"
  prefix: Sen. 1st Off.

- type: rank
  id: AU14RankCaptain
  name: "капітан"
  prefix: Cpt.

- type: rank
  id: AU14RankFlightCaptain
  name: "капітан польоту"
  prefix: Flt. Cpt.

# Orbital Manager

- type: rank
  id: AU14RankOrbitalManager
  name: "менеджер"
  prefix: Man.

- type: rank
  id: AU14RankSeniorOrbitalManager
  name: "старший менеджер"
  prefix: Sn. Man.

# Administrative Assistant

- type: rank
  id: AU14RankColonyAdminAssistant
  name: "асистент"
  prefix: Assist.

- type: rank
  id: AU14RankColonySeniorAdminAssistant
  name: "старший асистент"
  prefix: Sn. Assist.

# Corporate Assistant

- type: rank
  id: AU14RankWYJuniorAssistant
  name: "молодший асистент"
  prefix: Jr. Assist.

- type: rank
  id: AU14RankWYAssistant
  name: "асистент"
  prefix: Assist.

- type: rank
  id: AU14RankWYSeniorAssistant
  name: "старший асистент"
  prefix: Sn. Assist.

# Ambassadors

- type: rank
  id: AU14RankAmbassador
  name: "посол"
  prefix: Amb.


- type: rank
  id: AU14RankTWEAmbassador
  name: "верховний комісар"
  prefix: High Comm.
