# ├──[ Enlisted ]────────────────────────────────────────────────────┤
- type: rank
  id: AU14RankLACNSeamanRecruit
  name: "Матрос-рекрут"
  prefix: SR
  paygrade: E-1

- type: rank
  id: AU14RankLACNSeamanApprentice
  name: "Матрос-учень"
  prefix: SA
  paygrade: E-2

- type: rank
  id: AU14RankLACNSeaman
  name: "Матрос"
  prefix: SN
  paygrade: E-3

- type: rank
  id: AU14RankLACNPettyOfficerThirdClass
  name: "Старшина третього класу"
  prefix: PO3
  paygrade: E-4

- type: rank
  id: AU14RankLACNPettyOfficerSecondClass
  name: "Старшина другого класу"
  prefix: PO2
  paygrade: E-5

- type: rank
  id: AU14RankLACNPettyOfficerFirstClass
  name: "Старшина першого класу"
  prefix: PO1
  paygrade: E-6

- type: rank
  id: AU14RankLACNChiefPettyOfficer
  name: "Головний старшина"
  prefix: CPO
  paygrade: E-7

- type: rank
  id: AU14RankLACNSeniorChief
  name: "Старший головний старшина"
  prefix: SCPO
  paygrade: E-8

- type: rank
  id: AU14RankLACNMasterChief
  name: "Майстер-головний старшина" # HE WONT MISS!
  prefix: MCPO
  paygrade: E-9

# ├──[ Officers ]────────────────────────────────────────────────────┤
- type: rank
  id: AU14RankLACNSubEnsign
  name: "Молодший енсін"
  prefix: SENS
  paygrade: O-1

- type: rank
  id: AU14RankLACNEnsign
  name: "Енсін"
  prefix: ENS
  paygrade: O-2

- type: rank
  id: AU14RankLACNLieutenantJuniorGrade
  name: "Молодший лейтенант"
  prefix: LTJG
  paygrade: O-3

- type: rank
  id: AU14RankLACNLieutenant
  name: "Лейтенант"
  prefix: LT
  paygrade: O-4

- type: rank
  id: AU14RankLACNLieutenantCommander
  name: "Лейтенант-командер"
  prefix: LCDR
  paygrade: O-5

- type: rank
  id: AU14RankLACNCommander
  name: "Командер"
  prefix: CDR
  paygrade: O-6

- type: rank
  id: AU14RankLACNCaptain
  name: "Капітан"
  prefix: CAPT
  paygrade: O-7

- type: rank
  id: AU14RankLACNRearAdmiral
  name: "Контрадмірал"
  prefix: RADM
  paygrade: O-8

- type: rank
  id: AU14RankLACNViceAdmiral
  name: "Віцеадмірал"
  prefix: VADM
  paygrade: O-9

- type: rank
  id: AU14RankLACNAdmiral
  name: "Адмірал"
  prefix: ADM
  paygrade: O-10
