# enlisted
- type: rank
  id: RMC_Recruit
  name: "рекрут"
  prefix: Rct.
  paygrade: E1

- type: rank
  id: RMC_Marine
  name: "морпіх"
  prefix: Mne.
  paygrade: E2

- type: rank
  id: RMC_LanceCorporal
  name: "молодший капрал"
  prefix: LCpl.
  paygrade: E3

- type: rank
  id: RMC_Corporal
  name: "капрал"
  prefix: Cpl.
  paygrade: E4

- type: rank
  id: RMC_Sergeant
  name: "сержант"
  prefix: Sgt.
  paygrade: E5

- type: rank
  id: RMC_ColourSergeant
  name: "колор-сержант"
  prefix: CSgt.
  paygrade: E7

#  warrant Officers
- type: rank
  id: RMC_WarrantOfficer2
  name: "ворент-офіцер 2-го класу"
  prefix: WO2.
  paygrade: W1

- type: rank
  id: RMC_WarrantOfficer1
  name: "ворент-офіцер 1-го класу"
  prefix: WO1.
  paygrade: W2

# officers
- type: rank
  id: RMC_OfficerCader
  name: "офіцер-кадет"
  prefix: OCdt.

- type: rank
  id: RMC_2Lieutenant
  name: "молодший лейтенант"
  prefix: 2Lt.
  paygrade: O1

- type: rank
  id: RMC_Lieutenant
  name: "лейтенант"
  prefix: Lt.
  paygrade: O2

- type: rank
  id: RMC_Captain
  name: "капітан"
  prefix: Capt.
  paygrade: O3

#field officers
- type: rank
  id: RMC_Major
  name: "майор"
  prefix: Maj.
  paygrade: O4

- type: rank
  id: RMC_LieutenantColonel
  name: "підполковник"
  prefix: Lt Col.
  paygrade: O5

- type: rank
  id: RMC_Colonel
  name: "полковник"
  prefix: Col.
  paygrade: O6

- type: rank
  id: RMC_Brigadier
  name: "бригадир"
  prefix: Brig.
  paygrade: O7

- type: rank
  id: RMC_CommandantDeputy
  name: "заступник генерал-коменданта"
  prefix: DCG.
  paygrade: O7

# Generals
- type: rank
  id: RMC_MajorGeneral
  name: "генерал-майор"
  prefix: GenMaj.
  paygrade: O8

- type: rank
  id: RMC_LieutenantGeneral
  name: "генерал-лейтенант"
  prefix: Lt Gen.
  paygrade: O9

- type: rank
  id: RMC_General
  name: "генерал"
  prefix: Gen.
  paygrade: O10

- type: rank
  id: RMC_CommandantGeneral
  name: "генерал-комендант Королівської морської піхоти"
  prefix: CGRM.
  paygrade: O10

- type: rank
  id: RMC_CaptainGeneral
  name: "капітан-генерал Королівської морської піхоти"
  prefix: Capt-Gen.