- type: rank
  id: AU14RankUSASFTechnicalSergeant
  name: "технічний сержант"
  prefix: TSgt.
  paygrade: E6

- type: rank
  id: AU14RankUSASFMasterSergeant
  name: "майстер-сержант"
  prefix: MSgt.
  paygrade: E7

- type: rank
  id: AU14RankUSASFSMSgt
  name: "старший майстер-сержант"
  prefix: SMSgt.
  paygrade: E8

- type: rank
  id: AU14RankUSASFCMSgt
  name: "головний майстер-сержант"
  prefix: CMSgt.
  paygrade: E9

- type: rank
  id: AU14RankUSASFCCMSgt
  name: "командний головний майстер-сержант"
  prefix: CCM.
  paygrade: E9