# AU-14 ToDO add Sergeant Major of The Army/Marines


- type: rank
  id: RMCRankSergeantMajor
  name: "Старшина"
  prefix: SgtMaj.
  paygrade: E9E

- type: rank
  id: RMCRankMasterGunnerySergeant
  name: "Майстер-стрілець-сержант"
  prefix: MGySgt.
  paygrade: E9

- type: rank
  id: RMCRankFirstSergeant
  name: "Перший Сержант"
  prefix: 1stSgt.
  paygrade: E8E

- type: rank
  id: RMCRankMasterSergeant
  name: "Майстер-сержант"
  prefix: MSgt.
  paygrade: E8

- type: rank
  id: RMCRankGunnerySergeant
  name: "Стрілець-сержант"
  prefix: GySgt.
  paygrade: E7

- type: rank
  id: RMCRankStaffSergeant
  name: "Штаб-сержант"
  prefix: SSgt.
  paygrade: E6

- type: rank
  id: RMCRankSergeant
  name: "Сержант"
  prefix: Sgt.
  paygrade: E5

- type: rank
  id: RMCRankCorporal
  name: "Капрал"
  prefix: Cpl.
  paygrade: E4

- type: rank
  id: RMCRankLanceCorporal
  name: "Молодший Капрал"
  prefix: LCpl.
  paygrade: E3

- type: rank
  id: RMCRankPrivateFirstClass
  name: "Рядовий Першого Класу"
  prefix: PFC.
  paygrade: E2

- type: rank
  id: RMCRankPrivate
  name: "Рядовий"
  prefix: PVT.
  paygrade: E1

- type: rank
  id: RMCRankRecruit
  name: "Новобранець"
  prefix: Rct.
  paygrade: E0
