- type: rank
  id: RMCRankNavySeamanRecruit
  name: "Матрос-новобранець"
  prefix: SR.
  paygrade: E1

- type: rank
  id: RMCRankNavySeamanApprentice
  name: "Матрос-учень"
  prefix: SA.
  paygrade: E2

- type: rank
  id: RMCRankNavySeaman
  name: "Матрос"
  prefix: SN.
  paygrade: E3

- type: rank
  id: RMCRankNavyPettyOfficer3rdClass
  name: "Старший матрос 3-го класу"
  prefix: PO3.
  paygrade: E4

- type: rank
  id: RMCRankNavyPettyOfficer2ndClass
  name: "Старший матрос 2-го класу"
  prefix: PO2.
  paygrade: E5

- type: rank
  id: RMCRankNavyPettyOfficer1stClass
  name: "Старший матрос 1-го класу"
  prefix: PO1.
  paygrade: E6

- type: rank
  id: RMCRankNavyChiefPettyOfficer
  name: "Головний старший матрос"
  prefix: CPO.
  paygrade: E7

- type: rank
  id: RMCRankNavySeniorChiefPettyOfficer
  name: "Старший головний старший матрос"
  prefix: SCPO.
  paygrade: E8

- type: rank
  id: RMCRankNavyCommandSeniorChiefPettyOfficer
  name: "Командний старший головний старший матрос"
  prefix: CSCPO.
  paygrade: E8

- type: rank
  id: RMCRankNavyMasterChiefPettyOfficer
  name: "Майстер головний старший матрос"
  prefix: MCPO.
  paygrade: E9

- type: rank
  id: RMCRankNavyCommandMasterChiefPettyOfficer
  name: "Командний майстер головний старший матрос"
  prefix: CMCPO.
  paygrade: E9

# Commissioned Officers
- type: rank
  id: RMCRankNavyEnsign
  name: "Енсин"
  prefix: ENS.
  paygrade: O1

- type: rank
  id: RMCRankNavyLieutenantJuniorGrade
  name: "Лейтенант молодшого ступеня"
  prefix: LTJG.
  paygrade: O2

- type: rank
  id: RMCRankNavyLieutenant
  name: "Лейтенант"
  prefix: LT.
  paygrade: O3

- type: rank
  id: RMCRankNavyLieutenantCommander
  name: "Лейтенант-командор"
  prefix: LCDR.
  paygrade: O4

- type: rank
  id: RMCRankNavyCommander
  name: "Командор"
  prefix: CDR.
  paygrade: O5

- type: rank
  id: RMCRankNavyCaptain
  name: "Капітан"
  prefix: CAPT.
  paygrade: O6

- type: rank
  id: RMCRankNavyCommodore
  name: "Командор"
  prefix: CDRE.
  paygrade: O7

- type: rank
  id: RMCRankNavySeniorCommodore
  name: "Старший Командор"
  prefix: Snr CDRE.
  paygrade: O7

- type: rank
  id: RMCRankNavyRearAdmiralLowerHalf
  name: "Контр-адмірал (нижня половина)"
  prefix: RDML.
  paygrade: O8

- type: rank
  id: RMCRankNavyRearAdmiralUpperHalf
  name: "Контр-адмірал (верхня половина)"
  prefix: RADM.
  paygrade: O9

- type: rank
  id: RMCRankNavyViceAdmiral
  name: "Віце-адмірал"
  prefix: VADM.
  paygrade: O9

- type: rank
  id: RMCRankNavyAdmiral
  name: "Адмірал"
  prefix: ADM.
  paygrade: O10

- type: rank
  id: RMCRankNavyChiefOfNavalOperations
  name: "Начальник військово-морських операцій"
  prefix: CNO.
  paygrade: O10
