- type: rank
  id: RMCRankMajorGeneral
  name: "Генерал-майор"
  prefix: MajGen.
  paygrade: O8

- type: rank
  id: RMCRankBrigadierGeneral
  name: "Бригадний генерал"
  prefix: BGen.
  paygrade: O7

- type: rank
  id: RMCRankColonel
  name: "Полковник"
  prefix: Col.
  paygrade: O6

- type: rank
  id: RMCRankLieutenantColonel
  name: "Підполковник"
  prefix: LtCol.
  paygrade: O5

- type: rank
  id: RMCRankMajor
  name: "Майор"
  prefix: Maj.
  paygrade: O4

- type: rank
  id: RMCRankCaptain
  name: "Капітан"
  prefix: Capt.
  paygrade: O3

- type: rank
  id: RMCRankFirstLT
  name: "Перший Лейтенант"
  prefix: 1stLt.
  paygrade: O2

- type: rank
  id: RMCRankSecondLT
  name: "Молодший Лейтенант"
  prefix: 2ndLt.
  paygrade: O1

# AU-14 TO-DO Change these to WO1-WO5 instead of W1-W5

- type: rank
  id: RMCRankChiefWarrantOfficer5
  name: "Головний унтер-офіцер 5"
  prefix: CWarOff5.
  paygrade: W5

- type: rank
  id: RMCRankChiefWarrantOfficer4
  name: "Головний унтер-офіцер 4"
  prefix: CWarOff4.
  paygrade: W4

- type: rank
  id: RMCRankChiefWarrantOfficer3
  name: "Головний унтер-офіцер 3"
  prefix: CWarOff3.
  paygrade: W3

- type: rank
  id: RMCRankChiefWarrantOfficer
  name: "Головний унтер-офіцер 2"
  prefix:  CWarOff2.
  paygrade: W2

- type: rank
  id: RMCRankWarrantOfficer
  name: "Унтер-офіцер"
  prefix: WarOff.
  paygrade: W1
