# Whisper
- type: rank
  id: RMCRankProvostSectorMarshal
  name: "Секторний Маршал"
  prefix: PvSM.
  paygrade: O9

# Any admin with high law understanding
- type: rank
  id: RMCRankProvostSeniorMarshal
  name: "Старший Маршал"
  prefix: PvSnM.
  paygrade: O8

# Any admin with low law understanding, or wanting a lower rank
- type: rank
  id: RMCRankProvostMarshal
  name: "Маршал"
  prefix: PvM.
  paygrade: O7

# Any whitelisted CO
- type: rank
  id: RMCRankProvostDeputyMarshal
  name: "Заступник Маршала"
  prefix: PvDM.
  paygrade: O6

# Any player with high law understanding
- type: rank
  id: RMCRankProvostChiefInspector
  name: "Головний Інспектор"
  prefix: PvCI.
  paygrade: O5

# Any player with medium-low law understanding
- type: rank
  id: RMCRankProvostInspector
  name: "Інспектор Провоста"
  prefix: PvI.
  paygrade: O4

# Fax responder
- type: rank
  id: RMCRankProvostCommunicationsOfficer
  name: "Офіцер зв'язку"
  prefix: ComOff.
  paygrade: O2

# Any player with low law understanding, with guidance
- type: rank
  id: RMCRankProvostAdvisor
  name: "Старшина"
  prefix: SgtMaj.
  paygrade: E9E

# Any player with given objective, possible team leader
- type: rank
  id: RMCRankProvostProvostTeamLeader
  name: "Майстер-сержант"
  prefix: MSgt.
  paygrade: E8

# Any player with given objective, squad member
- type: rank
  id: RMCRankProvostProvostEnforcer
  name: "Штаб-сержант"
  prefix: SSgt.
  paygrade: E6
