- type: rank
  id: RMCRankCMBDeputy
  name: "Помічник CMB"
  prefix: Dep.
  paygrade: CMBD

- type: rank
  id: RMCRankCMBMarshal
  name: "Маршал CMB"
  prefix: Marshal
  paygrade: CMBM

- type: rank
  id: RMCRankCMBInvestigativeSynthetic
  name: "Слідчий синтетик CMB"
  prefix: Syn.

- type: rank
  id: RMCRankCMBRiotControlSynthetic
  name: "Синтетик контролю заворушень CMB"
  prefix: Syn.

- type: rank
  id: RMCRankCMBRiotControlOfficer
  name: "Офіцер контролю заворушень CMB"
  prefix: Off.

- type: rank
  id: RMCRankCMBMedicalTechnician
  name: "Медичний технік CMB"
  prefix: Med.

- type: rank
  id: RMCRankCMBBreachingTechnician
  name: "Технік-проривник CMB"
  prefix: Breach.

- type: rank
  id: RMCRankCMBSWATSpecialist
  name: "Спеціаліст SWAT CMB"
  prefix: Spec.

- type: rank
  id: RMCRankICBAgent
  name: "Агент Бюро Міжзоряної Торгівлі"
  prefix: Agent

- type: rank
  id: RMCRankICBCorporateLiaison
  name: "Корпоративний Лізон Бюро Міжзоряної Торгівлі"
  prefix: ICB Rep.
  paygrade: ICBL

- type: rank
  id: RMCRankIHROObserver
  name: "Спостерігач за міжзоряними правами життя"
  prefix: "Obsv."
  paygrade: ILRO
