- type: rank
  id: RMCRankWeYaOperator
  name: "Оператор"
  prefix: OPR.
  paygrade: PMC-OP

- type: rank
  id: RMCRankWeYaEnforcer
  name: "Енфорсер"
  prefix: ENF.
  paygrade: PMC-EN

- type: rank
  id: RMCRankWeYaVehicleSpecialist
  name: "Транспортний Спеціаліст"
  prefix: SPV.
  paygrade: PMC-VS

- type: rank
  id: RMCRankWeYaSupportSpecialist
  name: "Спеціаліст підтримки"
  prefix: SPS.
  paygrade: PMC-SS

- type: rank
  id: RMCRankWeYaMedicalSpecialist
  name: "Медичний Спеціаліст"
  prefix: SPM.
  paygrade: PMC-MS

- type: rank
  id: RMCRankWeYaWeaponSpecialist
  name: "Спеціаліст з озброєння"
  prefix: SPW.
  paygrade: PMC-WS

- type: rank
  id: RMCRankWeYaXenoSpecialist
  name: "Ксено-спеціаліст"
  prefix: SPX.
  paygrade: PMC-XS

- type: rank
  id: RMCRankWeYaTraumaSurgeon
  name: "Хірург-травматолог"
  prefix: Dr.
  paygrade: PMC-DOC

- type: rank
  id: RMCRankWeYaCorporateTechnician
  name: "Корпоративний Технік"
  prefix: TEC.
  paygrade: PMC-TEC

- type: rank
  id: RMCRankWeYaEliteResponder
  name: "Елітний Реагент"
  prefix: ELR.
  paygrade: PMC-ELR

- type: rank
  id: RMCRankWeYaEliteMedic
  name: "Елітний Медик"
  prefix: ELM.
  paygrade: PMC-ELM

- type: rank
  id: RMCRankWeYaEliteGunner
  name: "Елітний Стрілець"
  prefix: ELG.
  paygrade: PMC-ELG

- type: rank
  id: RMCRankWeYaPMCSynthetic
  name: "Синтетик"
  prefix: SYN.
  paygrade: PMC-SYN

- type: rank
  id: RMCRankWeYaTeamLeader
  name: "Лідер Команди"
  prefix: TML.
  paygrade: PMC-TL

- type: rank
  id: RMCRankWeYaFieldOperaionsLeader
  name: "Лідер польових операцій"
  prefix: FOL.
  paygrade: PMC-FOL

- type: rank
  id: RMCRankWeYaForceLeader
  name: "Лідер сил"
  prefix: FL.
  paygrade: PMC-FL

- type: rank
  id: RMCRankWeYaEliteTeamLeader
  name: "Елітний Лідер Команди"
  prefix: ETML.
  paygrade: PMC-ETL

- type: rank
  id: RMCRankWeYaSiteDirector
  name: "Директор Об'єкта PMC"
  prefix: Director
  paygrade: PMC-DIR

- type: rank
  id: RMCRankWeYaForceCommand
  name: "Командування PMC"
  prefix: FCO.
  paygrade: PMC-FCO

- type: rank
  id: RMCRankWeYaWhiteout
  name: "Бойовий загін «Вайтаут»"
  prefix: WO.
  paygrade: ???
